Creative_design/urls.py
from .views import handler404
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('about/', include('about.urls')),
    path('bag/', include('bag.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Creative_design.views.handler404'

bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_blogs, name='blogs'),
    path('create/', views.create_blog, name='create_blog'),
    path('<int:blog_id>/', views.detailed_blog_view, name='detailed_blog'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class blog(models.Model):
    title = models.CharField(max_length=150, null=False, blank=False)
    intro = models.TextField(max_length=80, null=False, blank=False, default='Intro')
    body = models.TextField(max_length=2000, null=False, blank=False)
    image = models.ImageField(upload_to='blogimages', null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True,
                                          verbose_name="date published")
    date_updated = models.DateTimeField(auto_now=True,
                                        verbose_name="date updated")
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_published']

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import ModelForm
from django import forms
from .models import blog


class BlogForm(forms.ModelForm):
    title = forms.CharField()
    intro = forms.CharField(widget=forms.Textarea)
    body = forms.CharField(widget=forms.Textarea)
    image = forms.ImageField()

    class Meta:
        model = blog
        fields = ['title', 'intro', 'body', 'image']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import blog
from .forms import BlogForm

# Create your views here.


def all_blogs(request):
    """  Blogs """

    blogs = blog.objects.all()
    context = {
        'blogs': blogs,
    }

    return render(request, 'blog/blogs.html', context)


@login_required
def create_blog(request):
    """  Create blog """
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            author = request.user
            obj.author = author
            form.save()
            messages.success(request, 'Successfully posted blog! returning to all blogs page')
            return redirect(reverse('blogs'))
        else:
            messages.error(request, 'Failed to post blog, please ensure the form is valid.')
    else:
        form = BlogForm()
    template = 'blog/create_blog.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def detailed_blog_view(request, blog_id):
    """ view selected blog """
    post = get_object_or_404(blog, pk=blog_id)

    template = 'blog/detailed_blog.html'
    context = {
        'post': post
    }
    return render(request, template, context)


@login_required
def edit_post(request, post_id):
    """ edit blog post. a"""

    post = get_object_or_404(blog, pk=post_id)

    user = request.user
    if user != post.author:
        messages.error(request, 'Sorry, only authors can do that.')
        return redirect(reverse('blogs'))

    print(user)
    print(post.author)

    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully Updated Post!')
            return redirect(reverse('blogs'))
    else:
        form = BlogForm(instance=post)

    template = 'blog/edit_blog.html'
    context = {
        'form': form,
        'post': post,
    }
    return render(request, template, context)


@login_required
def delete_post(request, post_id):
    """ Deletes blog post. """
    post = get_object_or_404(blog, pk=post_id)
    user = request.user
    if user != post.author:
        messages.error(request, 'Sorry, only authors can do that.')
        return redirect(reverse('blogs'))

    get_object_or_404(blog, pk=post_id).delete()
    messages.success(request, 'Your blog post has been successfully Deleted!.')
    return redirect(reverse('blogs'))

blog/templates/blog/blogs.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="overlay-2">
    <div class="container header-container">
        <div class="row">
            <div class="col text-center mt-3">
                <h1 id="blog-header" class="logo-font text-white">Create Your Blog Post Here</h1>
                <h2 id="blog-sub-header" class="text-white"> Why Should You Create A Blog Post? </h2>
                <br>
                <p id="blog-paragraph" class="text-white text-larger"> Want to share an experience with a product or
                    talk about what you would like to see next on our products list? Then please write your suggestion
                    or experience here!! If you are interested in what products we will release soon then please feel
                    free to
                    check out our <a id="social-media-link"
                        href="https://www.facebook.com/Creative-Design-111148724932377" target="_blank" rel="noopener">social media
                        page </a> for more information about that. <br> Thank You.
                </p>
                <br>
                <hr class="bg-ghostwhite">
                <!-- Create blog button -->
                <br>
                <div> <a href="{% url 'create_blog' %}"
                        class="shop-now-button btn btn-lg rounded-4 text-uppercase py-3">Create your blog
                        post</a> </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<br>
<br>
<br>
<!-- Blog post -->
<div class="white-overlay2"> </div>
<div class="container-fluid blog-headline">
    <div class="col-lg-12">
        {% for blog in blogs %}
        <div>
            <div class="text-warning">
                <h2 class="blog-title text-uppercase">{{ blog.title }}</h2>
                <p class="blog-author text-muted h6">By {{ blog.author }} | {{ blog.date_published |date:'D d M Y'}}</p>
                <p> {{blog.intro}}... </p>
                <a class="btn btn-warning read-more " data-toggle="collapse"
                    href="#collapseExample-{{ forloop.counter }}" role="button" aria-expanded="false"
                    aria-controls="collapseExample-{{ forloop.counter }}">
                    Read More &rarr;
                </a>
                <br>
                <div class="collapse" id="collapseExample-{{ forloop.counter }}">
                    <div class="read-more blog-body mx-auto">
                        {{ blog.body }}
                    </div>
                </div>
                <a href="{{ blog.image.url }}">
                    <img class="card-img-top img-fluid blog-image" src="{{ blog.image.url }}"
                        alt="Uploaded blog post image">
                </a>
                <br>
                <a class="btn btn-warning read-more"
                    href="{% url 'detailed_blog' blog.id %}" aria-controls="collapseExample-{{ forloop.counter }}">
                    View Post
                </a>
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/create_blog.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1 mt-5">
            <h1 class="text-pink text-center">ADD A BLOG POST</h1>
            <hr class="bg-orange">
            <form action="{% url 'create_blog' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Title -->
                <div>
                    <label class="text-pink" for="id_title">Title</label>
                    <input class="form-control mb-4" type="text" name="title" id="id_title" placeholder="Title"
                        autofocus required>
                </div>
                <!-- Intro -->
                <div>
                    <label class="text-pink" for="id_intro">Intro to your blog</label>
                    <input class="form-control" name="intro" id="id_intro"
                        placeholder="Add a short intro for your blog" required>
                </div>
                <!-- Body -->
                <div>
                    <label class="text-pink" for="id_body">Add a blog post</label>
                    <textarea class="form-control" rows="10" name="body" id="id_body"
                        placeholder="Write your story here..." required></textarea>
                </div>
                <!-- Image -->
                <div>
                    <label for="id_image"></label>
                    <p class="mb-1 text-pink">Upload image</p>
                    <input type="file" name="image" id="id_image" accept="image/*" required>
                    <p class="text-pink">Preferred size: Min height 100px, max height 600px.</p>

                <!-- Submit btn -->
                    <button class="btn post-button mt-1 mb-4" type="submit">POST</button>
                </div>
            </form>
            <!-- Back btn -->
            <a href="{% url 'blogs' %}" class="btn btn-outline-blue mt-1 mb-4">Back to blog</a>      
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/detailed_blog.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="pink-overlay"> </div>
<div class="header-container blog-headline">
    <div class="col-lg-12">
        <h1 class="text-uppercase text-warning">{{ post.title }}</h1>
        <p class="text-white">By {{ post.author }} | {{ post.date_published |date:'D d M Y'}}</p>
        <br>
        <br>
        <br>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid blog-headline">
    <div class="col-lg-12">
        <h2 class="text-uppercase text-white">{{ post.intro }}</h2>
        <div class="">
            {% if post.image %}
            <a href="{{ post.image.url }}" target="_blank">
                <img class="card-img-top img-fluid blog-image" src="{{ post.image.url }}" alt="blog-image">
            </a>
            {% else %}
            <a href="">
                <img class="card-img-top img-fluid blog-image" src="{{ MEDIA_URL }}noimage.png" alt="no-blog-image">
            </a>
            {% endif %}
        </div>
        <h3 class=" mb-5 text-white">{{ post.body }}</h3>

    </div>

    {%  if post.author != user %}

    {% else %}
        <a class="btn btn-outline-blue read-more" href="{% url 'edit_post' post.id %}"
            >
            Edit Post
        </a>
        <a class="btn btn-danger read-more" href="{% url 'delete_post' post.id %}"
            >
            Delete Post
        </a>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/edit_blog.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="header-container">
    <div class="row">
       <div class="col-12">
           
       </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1 mt-5">
            <h1 class="text-pink text-center">Edit Blog</h1>
            <hr class="bg-orange">
            <form action="{% url 'edit_post' post.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %} -->
                 <!-- Title -->
                 <div>
                    <label class="text-pink" for="id_title">Title</label>
                    {{ form.title }}
                </div>
                <!-- Intro -->
                <div>
                    <label class="text-pink" for="id_intro">Intro to your blog</label>
                    {{ form.intro }}
                </div>
                <!-- Body -->
                <div>
                    <label class="text-pink" for="id_body">Add a blog post</label>
                    {{ form.body }}
                </div>
                <!-- Image -->
                <div>
                    {{ form.image | as_crispy_field }}
                    <p class="text-pink">Preferred size: Min height 100px, max height 600px.</p>

                <!-- Submit btn -->
                    <button class="btn post-button mt-1 mb-4" type="submit">Update </button>
                    <a href="{% url 'detailed_blog' post.id %}"  class="btn btn-outline-blue mt-1 mb-4">Back to blog</a>      
                </div>
            </form>
            <!-- Back btn -->
        </div>
    </div>
</div>
{% endblock %}